USE [master]
GO
/****** Object:  Database [DOANJAVA]    Script Date: 16/03/22 9:47:11 PM ******/
CREATE DATABASE [DOANJAVA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DOANJAVA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DOANJAVA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DOANJAVA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DOANJAVA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DOANJAVA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DOANJAVA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DOANJAVA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DOANJAVA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DOANJAVA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DOANJAVA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DOANJAVA] SET ARITHABORT OFF 
GO
ALTER DATABASE [DOANJAVA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DOANJAVA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DOANJAVA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DOANJAVA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DOANJAVA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DOANJAVA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DOANJAVA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DOANJAVA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DOANJAVA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DOANJAVA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DOANJAVA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DOANJAVA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DOANJAVA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DOANJAVA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DOANJAVA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DOANJAVA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DOANJAVA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DOANJAVA] SET RECOVERY FULL 
GO
ALTER DATABASE [DOANJAVA] SET  MULTI_USER 
GO
ALTER DATABASE [DOANJAVA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DOANJAVA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DOANJAVA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DOANJAVA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DOANJAVA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DOANJAVA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DOANJAVA', N'ON'
GO
ALTER DATABASE [DOANJAVA] SET QUERY_STORE = OFF
GO
USE [DOANJAVA]
GO
/****** Object:  Table [dbo].[CT_DH]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CT_DH](
	[MA_DH] [bigint] NOT NULL,
	[MA_SAN_PHAM] [bigint] NOT NULL,
	[TEN_SAN_PHAM] [nvarchar](50) NULL,
	[S0_LUONG] [int] NULL,
	[THANH_TIEN] [money] NULL,
	[DON_GIA] [money] NULL,
	[TEN_NV] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MA_DH] ASC,
	[MA_SAN_PHAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DN_NV]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DN_NV](
	[TK_ID] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](50) NULL,
	[MA_NV] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TK_ID] ASC,
	[MA_NV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DON_DAT_HANG]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DON_DAT_HANG](
	[MA_DH] [bigint] NOT NULL,
	[MA_KH] [bigint] NOT NULL,
	[NGAY_LAP_DON] [datetime] NULL,
	[TONG_TIEN] [money] NULL,
	[GHI_CHU] [nvarchar](50) NULL,
	[NGAY_GIAO] [datetime] NULL,
	[TEN_KH] [nvarchar](50) NULL,
	[MA_NV] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MA_DH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_HANG]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG](
	[MA_KH] [bigint] NOT NULL,
	[TEN_KH] [nvarchar](50) NULL,
	[DIA_CHI] [nvarchar](50) NULL,
	[NGAY_SINH] [datetime] NULL,
	[SDT] [int] NULL,
	[EMAIL] [nvarchar](50) NULL,
	[GIOITINH] [int] NULL,
	[TAIKHOAN] [nvarchar](50) NULL,
	[MAUKHAU] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MA_KH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAN_VIEN]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAN_VIEN](
	[MA_NV] [bigint] NOT NULL,
	[TEN_NV] [nvarchar](50) NULL,
	[GT] [int] NULL,
	[DIACHI] [nvarchar](50) NULL,
	[EMAIL_NV] [nvarchar](50) NULL,
	[CHUCVU] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MA_NV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAN_PHAM]    Script Date: 16/03/22 9:47:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAN_PHAM](
	[MA_SAN_PHAM] [bigint] NOT NULL,
	[TEN_SAN_PHAM] [nvarchar](50) NULL,
	[DON_GIA] [money] NULL,
	[HINHANH] [nvarchar](100) NULL,
	[DON_VI_TINH] [int] NULL,
	[MO_TA] [nvarchar](200) NULL,
	[NGAY_NHAP_KHO] [datetime] NULL,
	[SL_ton] [int] NULL,
 CONSTRAINT [PK__SAN_PHAM__AEAADD69C1B88CAB] PRIMARY KEY CLUSTERED 
(
	[MA_SAN_PHAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[SAN_PHAM] ([MA_SAN_PHAM], [TEN_SAN_PHAM], [DON_GIA], [HINHANH], [DON_VI_TINH], [MO_TA], [NGAY_NHAP_KHO], [SL_ton]) VALUES (1, N'Bánh Cua Phô Mai', 25000.0000, N'./src/img/1.jpg', 1, NULL, CAST(N'2022-03-20T00:00:00.000' AS DateTime), 30)
GO
INSERT [dbo].[SAN_PHAM] ([MA_SAN_PHAM], [TEN_SAN_PHAM], [DON_GIA], [HINHANH], [DON_VI_TINH], [MO_TA], [NGAY_NHAP_KHO], [SL_ton]) VALUES (2, N'Bánh Tiramisu cacao', 30000.0000, N'./src/img/2.jpg', 1, NULL, CAST(N'2022-03-20T00:00:00.000' AS DateTime), 30)
GO
INSERT [dbo].[SAN_PHAM] ([MA_SAN_PHAM], [TEN_SAN_PHAM], [DON_GIA], [HINHANH], [DON_VI_TINH], [MO_TA], [NGAY_NHAP_KHO], [SL_ton]) VALUES (3, N'Bánh macaron', 50000.0000, N'./src/img/3.jpg', 10, NULL, CAST(N'2022-03-20T00:00:00.000' AS DateTime), 100)
GO
INSERT [dbo].[SAN_PHAM] ([MA_SAN_PHAM], [TEN_SAN_PHAM], [DON_GIA], [HINHANH], [DON_VI_TINH], [MO_TA], [NGAY_NHAP_KHO], [SL_ton]) VALUES (4, N'Bánh Donut', 50000.0000, N'./src/img/4.jpg', 1, NULL, CAST(N'2022-03-20T00:00:00.000' AS DateTime), 30)
GO
INSERT [dbo].[SAN_PHAM] ([MA_SAN_PHAM], [TEN_SAN_PHAM], [DON_GIA], [HINHANH], [DON_VI_TINH], [MO_TA], [NGAY_NHAP_KHO], [SL_ton]) VALUES (5, N'Bánh crepe cầu vồng', 50000.0000, N'./src/img/5.jpg', 1, NULL, CAST(N'2022-03-20T00:00:00.000' AS DateTime), 30)
GO
ALTER TABLE [dbo].[CT_DH]  WITH CHECK ADD FOREIGN KEY([MA_DH])
REFERENCES [dbo].[DON_DAT_HANG] ([MA_DH])
GO
ALTER TABLE [dbo].[CT_DH]  WITH CHECK ADD  CONSTRAINT [FK__CT_DH__MA_SAN_PH__31EC6D26] FOREIGN KEY([MA_SAN_PHAM])
REFERENCES [dbo].[SAN_PHAM] ([MA_SAN_PHAM])
GO
ALTER TABLE [dbo].[CT_DH] CHECK CONSTRAINT [FK__CT_DH__MA_SAN_PH__31EC6D26]
GO
ALTER TABLE [dbo].[DN_NV]  WITH CHECK ADD FOREIGN KEY([MA_NV])
REFERENCES [dbo].[NHAN_VIEN] ([MA_NV])
GO
ALTER TABLE [dbo].[DON_DAT_HANG]  WITH CHECK ADD FOREIGN KEY([MA_KH])
REFERENCES [dbo].[KHACH_HANG] ([MA_KH])
GO
ALTER TABLE [dbo].[DON_DAT_HANG]  WITH CHECK ADD FOREIGN KEY([MA_NV])
REFERENCES [dbo].[NHAN_VIEN] ([MA_NV])
GO
USE [master]
GO
ALTER DATABASE [DOANJAVA] SET  READ_WRITE 
GO
